# -*- coding: utf-8 -*-
import RubiksCube
import MovementCube

cube = RubiksCube.RubiksCube()
mc = MovementCube.Movement()
mc.right(cube, 0)
mc.up(cube, 4)
mc.invDown(cube, 3)
print(cube.getTab())
print("######################################################")
mc.x(cube)
print(cube.getTab())
print("######################################################")
mc.x(cube)
print(cube.getTab())
print("######################################################")
mc.x(cube)
print(cube.getTab())
print("######################################################")
mc.y(cube)
print(cube.getTab())
print("######################################################")
mc.y(cube)
print(cube.getTab())
print("######################################################")
mc.y(cube)
print(cube.getTab())
print("######################################################")
