import Movement as m

#Classe permettant d'échanger deux cubes
class Swap:
    #Fonction échangeant deux côtés (avec des coins aussi donc à faire avant les coins)
    def swapEdges:
        m.right()
        m.up()
        m.inverseRight()
        m.inverseUp() 
        m.inverseRight() 
        m.front()
        m.right()
        m.right()
        m.inverseUp() 
        m.inverseRight() 
        m.inverseUp() 
        m.right()
        m.up()
        m.inverseRight()
        m.inverseFront()
    #Fonction échangeant deux coins
    def swapCorners:
        m.right()
        m.inverseUp()
        m.inverseRight()
        m.inverseUp()
        m.right()
        m.up()
        m.inverseRight()
        m.inverseFront()
        m.right()
        m.up()
        m.inverseRight()
        m.inverseUp()
        m.inverseRight()
        m.front()
        m.right()
    #Fonction parité: à faire si le nombre de swap est impair (les swap modifient aussi quelques autres trucs une fois sur 2)
    #Si ne marche pas, faire un "triangle" --> en gros faire 3 swap qui reviennent au même endroit
    def parity:
        m.right()
        m.inverseUp()
        m.inverseRight()
        m.inverseUp()
        m.right()
        m.up()
        m.right()
        m.down()
        m.inverseRight()
        m.inverseUp()
        m.right()
        m.inverseDown()
        m.inverseRight()
        m.up()
        m.up()
        m.inverseRight()
        m.inverseUp()

